/**
 * Narrative scoring + HGB-impact weighting (SITE-HOME-04.5 / Layer 4.5).
 *
 * Two pure functions that drive the recap-mode editorial layer:
 *
 *   1. `narrativeScore(game)` — returns 0-100 for how "story-worthy" a
 *      completed game is. Used to decide if a game appears as an
 *      `ArtifactGame` card in the wall. Below threshold (30) the game
 *      drops to the FINAL SCORES strip only.
 *
 *   2. `narrativeWeight(slug, data)` — returns 0-100 for sorting wall
 *      artifacts by HGB IMPACT. Each artifact type has its own formula
 *      so a 1000-point milestone reliably beats a tepid hat trick, and
 *      a Cup-clinching game beats a regular-season streak.
 *
 * Both are pure: no I/O, no side effects, deterministic. They operate on
 * the artifact `data` payloads validated by `artifact-schemas.ts` plus a
 * handful of *narrative metadata* fields that the eventual Python
 * pipeline will populate but the artifact components don't render.
 *
 * ────────────────────────────────────────────────────────────────────────
 * CROSS-REPO CONTRACT — fields the Python bot must populate
 * ────────────────────────────────────────────────────────────────────────
 *
 * Per-game fields used by `narrativeScore`:
 *   game.state           : 'reg' | 'ot' | 'so'         (existing — derive from state.label)
 *   game.score.home      : number                       (existing)
 *   game.score.away      : number                       (existing)
 *   game.max_wp_swing    : number 0-1                   (NEW — max delta in win prob during game)
 *   game.max_deficit_overcome : number                  (NEW — biggest deficit the eventual winner overcame, in goals)
 *   game.had_milestone   : boolean                      (NEW — true if a player milestone fired during this game)
 *   game.is_clincher     : boolean                      (NEW — true if this game ended a series)
 *   game.home_sog        : number                       (NEW — total shots on goal, home)
 *   game.away_sog        : number                       (NEW — total shots on goal, away)
 *
 * Per-artifact fields used by `narrativeWeight`:
 *   milestone.career_value : number                     (NEW — e.g. 1000 for "1000 career points")
 *   milestone.threshold    : number                     (NEW — round-number threshold this milestone crossed)
 *   hattrick.xg            : number                     (NEW — individual xG on the night)
 *   goalie.gsax            : number                     (NEW — numeric, parsed from "+2.1")
 *   clinch.round           : 'R1'|'R2'|'ECF'|'WCF'|'SCF'|'Cup'  (NEW — round label for round_bonus)
 *   hot.streak_length      : number                     (NEW — N games in the streak)
 *   cold.streak_length     : number                     (NEW)
 *   line.combined_xg       : number                     (NEW — combined 5v5 xG generated by the trio)
 *   game.* (see above)
 *
 * Most existing artifact components carry stringly-typed display values
 * (e.g. `goalie.gsax: "+2.1"`); the narrative metadata adds parallel
 * numeric fields for sort math. The bot can keep both — display strings
 * are user-facing, numerics are sort-only.
 */

// ── Helpers ─────────────────────────────────────────────────────────────────

function clamp(n: number, min = 0, max = 100): number {
  if (!Number.isFinite(n)) return min;
  return Math.max(min, Math.min(max, n));
}

/**
 * Parse the leading number out of a string like "+2.1" or "-0.6". Returns
 * 0 on garbage input. Used to coerce display strings (gsax, hgb scores)
 * into numerics for sort math.
 */
function leadingNumber(s: unknown): number {
  if (typeof s === 'number') return s;
  if (typeof s !== 'string') return 0;
  const m = s.match(/-?\d+(?:\.\d+)?/);
  return m ? parseFloat(m[0]) : 0;
}

/** State derivation from the existing `state.label` display string. */
function deriveState(game: NarrativeGame): 'reg' | 'ot' | 'so' {
  if (typeof game.state === 'string') return game.state;
  if (game.state?.kind) return game.state.kind;
  const label = game.state?.label?.toUpperCase?.() ?? '';
  if (label.includes('SO')) return 'so';
  if (label.includes('OT')) return 'ot';
  return 'reg';
}

// ── Game shape (loose-typed at the boundary) ────────────────────────────────

/**
 * `narrativeScore` accepts the rich ArtifactGame payload PLUS the
 * narrative-metadata fields documented in the contract above. The game
 * shape is loose-typed because the bot may emit extra fields the wall
 * doesn't render. Each accessed field is null-checked.
 */
export interface NarrativeGame {
  state?: string | { label?: string; kind?: 'reg' | 'ot' | 'so' };
  score?: { home?: number; away?: number };
  max_wp_swing?: number;
  max_deficit_overcome?: number;
  had_milestone?: boolean;
  is_clincher?: boolean;
  home_sog?: number;
  away_sog?: number;
}

// ── narrativeScore ──────────────────────────────────────────────────────────

/**
 * Score a completed game on its narrative weight (0-100). Used to gate
 * wall inclusion: games with `narrativeScore() >= 30` get a card; the
 * rest live only in the FINAL SCORES strip.
 *
 * Components are additive and the result is clamped to [0, 100]. Kept
 * simple on purpose so the threshold can be tuned by eye on a real
 * playoff night without diving into a regression model.
 */
export function narrativeScore(game: NarrativeGame): number {
  let s = 0;
  const home = game.score?.home ?? 0;
  const away = game.score?.away ?? 0;
  const diff = Math.abs(home - away);
  const state = deriveState(game);

  // OT / SO finish — playoff hockey's signature drama.
  if (state === 'ot' || state === 'so') s += 25;

  // Late-game WP swing — "the game was either team's at some point".
  if (typeof game.max_wp_swing === 'number' && game.max_wp_swing > 0.30) {
    s += 20;
  }

  // Score margin >= 5 — blowouts are their own kind of story.
  if (diff >= 5) s += 15;

  // Comeback from 3+ goal deficit — instant "did you see this" narrative.
  if (typeof game.max_deficit_overcome === 'number' && game.max_deficit_overcome >= 3) {
    s += 25;
  }

  // Shutout — goalie gets a card; game itself is also notable.
  if (home === 0 || away === 0) s += 15;

  // Milestone fired during this game — the milestone card pairs with this
  // game card via supporting_hero on the hero, but the wall benefits too.
  if (game.had_milestone === true) s += 15;

  // Series-clinching game — playoff context only; ignored in regular
  // season since `is_clincher` is always false there.
  if (game.is_clincher === true) s += 20;

  // 1-goal game — overlaps with OT bonus on purpose; an OT 4-3 game
  // gets +25 (OT) + +10 (1-goal) = +35 just from finish style.
  if (diff === 1) s += 10;

  // Combined SOG > 70 — fast, frenetic game with lots of action.
  const sog = (game.home_sog ?? 0) + (game.away_sog ?? 0);
  if (sog > 70) s += 10;

  return clamp(s);
}

// ── narrativeWeight ─────────────────────────────────────────────────────────

const _ROUND_BONUS: Record<string, number> = {
  R1: 0,
  R2: 10,
  ECF: 20,
  WCF: 20,
  SCF: 30, // semi-finals (legacy alias for ECF/WCF)
  Cup: 40,
};

export type NarrativeArtifactSlug =
  | 'game'
  | 'hot'
  | 'cold'
  | 'milestone'
  | 'line'
  | 'matchup'
  | 'clinch'
  | 'season'
  | 'hattrick'
  | 'stars'
  | 'goalie';

/**
 * Weight an artifact for HGB-IMPACT sort (0-100). Each artifact slug has
 * its own formula — see the table in the brief for tuning notes.
 *
 * The `data` parameter is the artifact's data payload. Missing narrative
 * metadata falls back to a sensible baseline so an under-populated card
 * still sorts in a reasonable place.
 */
export function narrativeWeight(
  slug: NarrativeArtifactSlug,
  data: Record<string, any>,
): number {
  switch (slug) {
    case 'milestone': {
      // 30 baseline + up to +50 scaled to threshold-crossing magnitude.
      // 1000 career pts crossing the 1000 threshold = 30 + 50 = 80.
      const career = Number(data?.career_value ?? 0);
      const threshold = Number(data?.threshold ?? 0);
      if (!career || !threshold) return 50; // fallback for under-populated cards
      return clamp(30 + Math.min(50, (career / threshold) * 50));
    }

    case 'hattrick': {
      // 60 baseline + up to +20 from individual xG. xG=2.0 → 60 + 20 = 80.
      const xg = Number(data?.xg ?? 0);
      return clamp(60 + Math.min(20, (xg / 2) * 20));
    }

    case 'goalie': {
      // 40 baseline + up to +50 scaled to gsax. gsax=2.0 → 40 + 60 → cap at 90.
      const gsax = leadingNumber(data?.gsax);
      return clamp(40 + Math.min(50, gsax * 30), 0, 90);
    }

    case 'clinch': {
      // 60 baseline + round_bonus. R1=60, R2=70, ECF/WCF=80, Cup=100.
      const round = String(data?.round ?? 'R1');
      const bonus = _ROUND_BONUS[round] ?? 0;
      return clamp(60 + bonus);
    }

    case 'game': {
      // Reuse narrativeScore — same heuristic, different surface.
      return narrativeScore(data as NarrativeGame);
    }

    case 'hot': {
      // 30 baseline + 5 per streak game, cap 70.
      const len = Number(data?.streak_length ?? 0);
      return clamp(Math.min(70, 30 + len * 5));
    }

    case 'cold': {
      // 25 baseline + 4 per drought game, cap 60.
      const len = Number(data?.streak_length ?? 0);
      return clamp(Math.min(60, 25 + len * 4));
    }

    case 'line': {
      // 40 baseline + up to +40 from combined xG. 4.0 combined xG = 40 + 40 = 80.
      const cxg = Number(data?.combined_xg ?? 0);
      return clamp(40 + Math.min(40, cxg * 10));
    }

    case 'stars':
      // Three stars is a postgame ritual; relevant but rarely tops sort.
      return 35;

    case 'season':
      // Season cards are editorial overlays — only visible under ALL.
      // Low weight so they don't dominate the sort.
      return 20;

    case 'matchup':
      // Matchup cards are pre-game artifacts — not part of recap. Return
      // 0 so any stragglers fall to the bottom.
      return 0;

    default:
      return 20;
  }
}
